### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [ws-engineering/resize-script#1]
Greetings @ws-engineering

I've noticed this is a new project
and I wanted to collaborate delivering
a _free_ logo proposal, if that's something that
may interest you, let me know!

I'm a Graphic Designer and an Open Source Enthusiast!
Cheers!
-Luigi.

**Comment by hamxabaig** [comment]
Hey @LuigiBaute thanks for the proposal but its just a script for an article nothing much. But I appreciate your effort 👌 

Thanks
